### ISSUE TITLE
Separate user and dev docs

### ISSUE THREAD

**Issue by stephanielee9** [SupertechLabs/client-superstaq#363]
Re https://github.com/SupertechLabs/server-superstaq/issues/1728

**Comment by vtomole** [comment]
@dhirpalshah recently ran into this issue where https://docs-superstaq.readthedocs.io/en/stable/get_started/installation.html wasn't clear when he should be installing for dev or for user.

**Comment by stephanielee9** [comment]
@vtomole now that https://github.com/SupertechLabs/client-superstaq/pull/485 is closed, is it good to close this issue? Or do we still want to work on this: https://github.com/SupertechLabs/server-superstaq/issues/1728?

**Comment by stephanielee9** [comment]
Not relevant for making dev docs public
