### ISSUE TITLE
Can't submit jobs through `css` to `ibmq_qasm_simulator`

### ISSUE THREAD

**Issue by stephanielee9** [SupertechLabs/client-superstaq#401]
### What is happening?

I can submit jobs through `qss` to `ibmq_qasm_simulator`, but not through `css`. (I can submit to the Hilbert simulator through both `css` and `qss`). 

Error is `Status code: 500, Message: 'Non-retriable error making request to SuperstaQ API, Internal Server Error'`. Logs say `AttributeError: 'NoneType' object has no attribute 'serialized_job'`. Note that @vtomole is running the same code and not getting any errors.

### How can we reproduce the issue?

```
import cirq
import cirq_superstaq as css

q0 = cirq.LineQubit(0)
q1 = cirq.LineQubit(1)

circuit = cirq.Circuit(cirq.H(q0), cirq.CNOT(q0, q1), cirq.measure(q0))

service = css.Service(
    api_key="<token>",
    verbose=True,
)

# Submitting a circuit to "ibmq_qasm_simulator". Providing the "dry-run" method parameter instructs SuperstaQ to simulate the circuit, and is available to free trial users.
job = service.create_job(circuit=circuit, repetitions=1, target="ibmq_qasm_simulator")
print("This is the job that's created ", job.status())
print(job.counts())
```

### What should happen?

The code above should return counts.

### Environment

- **SuperstaQ version**: 
- **general-superstaq version**: 0.3.21
- **cirq-superstaq version**: 0.3.21
- **qiskit-superstaq version**: 0.3.21
- **Operating system**: 
- **Python version**: 
- **Any other relevant dependencies**:

**Comment by dowusu-antwi** [comment]
@stephanielee9 Are you still getting this issue? I just ran it here:
![image](https://user-images.githubusercontent.com/18367737/229590079-e6cdd882-49b3-4f1f-a621-90c1b780b894.png)

**Comment by stephanielee9** [comment]
Not getting the error either anymore - closing for now
