### ISSUE TITLE
Include metadata for compiled qiskit circuit

### ISSUE THREAD

**Issue by ColinCampbellCQ** [SupertechLabs/client-superstaq#453]
### What is happening?

When I use cq_compile on a qiskit QuantumCircuit that has metadata stored in circuit.metadata, the compiled circuit does not carry over that metadata.

### What are the current alternatives?

I work around this inconvenience by keeping the original circuit around and accessing its metadata later, or I just set the compiled circuit's metadata to be equal to that of the original.

### Any additional context?

![image](https://user-images.githubusercontent.com/108485140/236267585-fcae631b-9a38-4e37-8caa-e491008528b8.png)

**Comment by bharat-thotakura** [comment]
@ColinCampbellCQ, this issue has now been fixed with the latest client-superstaq release
